package demo

import (
	"time"

	"github.com/GF6599/lazylab/internal/gitlab"
)

// refTime is the fixed anchor for all demo timestamps, ensuring deterministic
// output across runs (important for reproducible VHS recordings).
var refTime = time.Date(2025, 6, 15, 10, 0, 0, 0, time.UTC)

func demoProjects() []gitlab.ProjectNode {
	return []gitlab.ProjectNode{
		{
			ID:                1001,
			Name:              "api-gateway",
			PathWithNamespace: "acme-corp/api-gateway",
			Description:       "Edge proxy with rate limiting, auth, and request routing",
			WebURL:            "https://gitlab.example.com/acme-corp/api-gateway",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/api-gateway.git",
			LastActivityAt:    refTime.Add(-1 * time.Hour),
			StarCount:         42,
			Visibility:        "internal",
			DefaultBranch:     "main",
		},
		{
			ID:                1002,
			Name:              "auth-service",
			PathWithNamespace: "acme-corp/auth-service",
			Description:       "OAuth2 / OIDC identity provider with LDAP backend",
			WebURL:            "https://gitlab.example.com/acme-corp/auth-service",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/auth-service.git",
			LastActivityAt:    refTime.Add(-3 * time.Hour),
			StarCount:         38,
			Visibility:        "internal",
			DefaultBranch:     "main",
		},
		{
			ID:                1003,
			Name:              "web-frontend",
			PathWithNamespace: "acme-corp/web-frontend",
			Description:       "React SPA for the customer dashboard",
			WebURL:            "https://gitlab.example.com/acme-corp/web-frontend",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/web-frontend.git",
			LastActivityAt:    refTime.Add(-5 * time.Hour),
			StarCount:         27,
			Visibility:        "internal",
			DefaultBranch:     "main",
		},
		{
			ID:                1004,
			Name:              "cli-tools",
			PathWithNamespace: "acme-corp/cli-tools",
			Description:       "Internal developer CLI (Go + Cobra)",
			WebURL:            "https://gitlab.example.com/acme-corp/cli-tools",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/cli-tools.git",
			LastActivityAt:    refTime.Add(-8 * time.Hour),
			StarCount:         15,
			Visibility:        "internal",
			DefaultBranch:     "main",
		},
		{
			ID:                1005,
			Name:              "data-pipeline",
			PathWithNamespace: "acme-corp/data-pipeline",
			Description:       "ETL jobs for warehouse ingestion (Airflow + dbt)",
			WebURL:            "https://gitlab.example.com/acme-corp/data-pipeline",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/data-pipeline.git",
			LastActivityAt:    refTime.Add(-12 * time.Hour),
			StarCount:         19,
			Visibility:        "private",
			DefaultBranch:     "main",
		},
		{
			ID:                1006,
			Name:              "infra-terraform",
			PathWithNamespace: "acme-corp/infra-terraform",
			Description:       "AWS infrastructure as code (VPC, EKS, RDS)",
			WebURL:            "https://gitlab.example.com/acme-corp/infra-terraform",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/infra-terraform.git",
			LastActivityAt:    refTime.Add(-24 * time.Hour),
			StarCount:         31,
			Visibility:        "private",
			DefaultBranch:     "main",
		},
		{
			ID:                1007,
			Name:              "mobile-app",
			PathWithNamespace: "acme-corp/mobile-app",
			Description:       "Cross-platform mobile app (React Native)",
			WebURL:            "https://gitlab.example.com/acme-corp/mobile-app",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/mobile-app.git",
			LastActivityAt:    refTime.Add(-36 * time.Hour),
			StarCount:         22,
			Visibility:        "internal",
			DefaultBranch:     "develop",
		},
		{
			ID:                1008,
			Name:              "notification-service",
			PathWithNamespace: "acme-corp/notification-service",
			Description:       "Email, SMS, and push notification dispatcher",
			WebURL:            "https://gitlab.example.com/acme-corp/notification-service",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/notification-service.git",
			LastActivityAt:    refTime.Add(-48 * time.Hour),
			StarCount:         11,
			Visibility:        "internal",
			DefaultBranch:     "main",
		},
		{
			ID:                1009,
			Name:              "docs-site",
			PathWithNamespace: "acme-corp/docs-site",
			Description:       "Public documentation built with MkDocs Material",
			WebURL:            "https://gitlab.example.com/acme-corp/docs-site",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/docs-site.git",
			LastActivityAt:    refTime.Add(-72 * time.Hour),
			StarCount:         8,
			Visibility:        "public",
			DefaultBranch:     "main",
		},
		{
			ID:                1010,
			Name:              "shared-libs",
			PathWithNamespace: "acme-corp/shared-libs",
			Description:       "Common Go packages (logging, tracing, middleware)",
			WebURL:            "https://gitlab.example.com/acme-corp/shared-libs",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/shared-libs.git",
			LastActivityAt:    refTime.Add(-96 * time.Hour),
			StarCount:         34,
			Visibility:        "internal",
			DefaultBranch:     "main",
		},
		{
			ID:                1011,
			Name:              "monitoring-stack",
			PathWithNamespace: "acme-corp/monitoring-stack",
			Description:       "Prometheus, Grafana, and Alertmanager configs",
			WebURL:            "https://gitlab.example.com/acme-corp/monitoring-stack",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/monitoring-stack.git",
			LastActivityAt:    refTime.Add(-120 * time.Hour),
			StarCount:         16,
			Visibility:        "private",
			DefaultBranch:     "main",
		},
		{
			ID:                1012,
			Name:              "ml-experiments",
			PathWithNamespace: "acme-corp/ml-experiments",
			Description:       "ML model training and evaluation notebooks",
			WebURL:            "https://gitlab.example.com/acme-corp/ml-experiments",
			SSHURLToRepo:      "git@gitlab.example.com:acme-corp/ml-experiments.git",
			LastActivityAt:    refTime.Add(-144 * time.Hour),
			StarCount:         9,
			Visibility:        "private",
			DefaultBranch:     "main",
		},
	}
}
