package ui

import "github.com/charmbracelet/lipgloss"

var (
	rosePineBase   = lipgloss.Color("#232136")
	rosePineText   = lipgloss.Color("#e0def4")
	rosePineMuted  = lipgloss.Color("#6e6a86")
	rosePineSubtle = lipgloss.Color("#908caa")
	rosePineRose   = lipgloss.Color("#ebbcba")
	rosePinePine   = lipgloss.Color("#31748f")
	rosePineFoam   = lipgloss.Color("#9ccfd8")
	rosePineGold   = lipgloss.Color("#f6c177")
	rosePineIris   = lipgloss.Color("#c4a7e7")
	rosePineLove   = lipgloss.Color("#eb6f92")
)

var (
	titleStyle        = lipgloss.NewStyle().Bold(true).Foreground(rosePineIris)
	itemStyle         = lipgloss.NewStyle().Foreground(rosePineText)
	selectedItemStyle = lipgloss.NewStyle().Bold(true).Foreground(rosePineRose)
	statusStyle       = lipgloss.NewStyle().Faint(true).Foreground(rosePineSubtle)
	errorStyle        = lipgloss.NewStyle().Foreground(rosePineLove)
	searchStyle       = lipgloss.NewStyle().Faint(true).Foreground(rosePineSubtle)
	progressStyle     = lipgloss.NewStyle().Faint(true).Foreground(rosePineMuted)
	pipelineSuccess   = lipgloss.NewStyle().Bold(true).Foreground(rosePinePine)
	pipelineFailed    = lipgloss.NewStyle().Bold(true).Foreground(rosePineLove)
	pipelineRunning   = lipgloss.NewStyle().Bold(true).Foreground(rosePineFoam)
	pipelinePending   = lipgloss.NewStyle().Bold(true).Foreground(rosePineGold)
	pipelineCanceled  = lipgloss.NewStyle().Bold(true).Foreground(rosePineMuted)
	pipelineSkipped   = lipgloss.NewStyle().Bold(true).Foreground(rosePineSubtle)
	pipelineUnknown   = lipgloss.NewStyle().Bold(true).Foreground(rosePineMuted)
)

var (
	paneBorderStyle          = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(rosePineSubtle)
	paneBorderFocusStyle     = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(rosePineRose)
	explorerHeaderStyle      = lipgloss.NewStyle().Bold(true).Foreground(rosePineIris)
	explorerFocusHeaderStyle = lipgloss.NewStyle().Bold(true).Foreground(rosePineRose)
	detailHeaderStyle        = lipgloss.NewStyle().Bold(true).Foreground(rosePineIris)
	detailDividerStyle       = lipgloss.NewStyle().Foreground(rosePineSubtle)
	detailLabelStyle         = lipgloss.NewStyle().Foreground(rosePineMuted)
	detailValueStyle         = lipgloss.NewStyle().Foreground(rosePineText)
	explorerPathStyle        = lipgloss.NewStyle().Foreground(rosePineMuted)
	explorerHintStyle        = lipgloss.NewStyle().Foreground(rosePineSubtle)
	explorerErrorStyle       = lipgloss.NewStyle().Foreground(rosePineLove)
	explorerDirStyle         = lipgloss.NewStyle().Foreground(rosePinePine)
	explorerFileStyle        = lipgloss.NewStyle().Foreground(rosePineText)
	explorerSelectedStyle    = lipgloss.NewStyle().Bold(true).Foreground(rosePineRose)
)
